version: '3'
services:
  db:
    image: mysql/mysql-server:8.0
    container_name: mysql_service
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"    
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    env_file: .db.env
    environment:
      - TZ=Asia/Seoul
    networks:
      - db_network
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 2s
      retries: 100
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - ./app/:/app/src
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db_network
networks:
  db_network:
    driver: bridge