# Generated by Django 4.1.2 on 2023-01-18 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contents',
            table='post_content',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
