# Generated by Django 4.1.2 on 2022-11-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uuid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=20, unique=True)),
                ('pw', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
