# Generated by Django 4.1.2 on 2023-01-18 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='user',
        ),
    ]
